//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyChat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyChatDBEntities : DbContext
    {
        public MyChatDBEntities()
            : base("name=MyChatDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblKullanici> tblKullanici { get; set; }
        public virtual DbSet<tblMesajlar> tblMesajlar { get; set; }
        public virtual DbSet<tblSohbetler> tblSohbetler { get; set; }
        public virtual DbSet<tblSohbetListeleri> tblSohbetListeleri { get; set; }
        public virtual DbSet<tblSohbetTipleri> tblSohbetTipleri { get; set; }
    }
}
