//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        public int kullanıcıID { get; set; }
        public string kullanıcıAdi { get; set; }
        public string kullaniciEposta { get; set; }
        public string kullaniciSifre { get; set; }
        public System.DateTime kullaniciSonGirisTarihi { get; set; }
    }
}
