//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSohbetListeleri
    {
        public int sohbetUyeListesiID { get; set; }
        public int kullanıcıID { get; set; }
        public System.DateTime dahilOlmaTarihi { get; set; }
    }
}
